apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  secretName: wildcard-certificate
  dnsNames:
    - "*.queerintech.org"
  issuerRef:
    name: dns01-issuer
    kind: ClusterIssuer
